/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "cakzfgkuzeblnbvhujkv"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNha3pmZ2t1emVibG5idmh1amt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4OTQwNTksImV4cCI6MjA3MjQ3MDA1OX0.ZKtsjIGvt3p3RHph4SyKcZs-3x-bjCF6zmG3AVRA76M"